menu_index:
    path:     /
    defaults: { _controller: "AppBundle:Menu:index" }
    methods:  GET

menu_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Menu:show" }
    methods:  GET

menu_new:
    path:     /new
    defaults: { _controller: "AppBundle:Menu:new" }
    methods:  [GET, POST]

menu_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Menu:edit" }
    methods:  [GET, POST]

menu_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Menu:delete" }
    methods:  DELETE
